### ISSUE TITLE
peers_mutex_ deadlock

### ISSUE THREAD

**Issue by MatusKysel** [Taraxa-project/taraxa-node#1029]
### Description
after recent changes our node deadlocks on `peers_mutex_` mutex. 
Last time back trace looked like this 

```
#6  0x00007fd6533049d3 in boost::shared_mutex::lock (this=0x556f3e1f15c8) at /root/.conan/data/boost/1.71.0/_/_/package/4df9db66fa51fc4b08f492b90f2f6e935011ec3a/include/boost/bind/bind.hpp:1287
#7  boost::unique_lock<boost::shared_mutex>::lock (this=0x7fd5b27f2f00) at /root/.conan/data/boost/1.71.0/_/_/package/4df9db66fa51fc4b08f492b90f2f6e935011ec3a/include/boost/thread/lock_types.hpp:346
#8  0x00007fd653464c2e in boost::unique_lock<boost::shared_mutex>::unique_lock (m_=..., this=0x7fd5b27f2f00) at /root/.conan/data/boost/1.71.0/_/_/package/4df9db66fa51fc4b08f492b90f2f6e935011ec3a/include/boost/thread/lock_types.hpp:121
#9  taraxa::TaraxaCapability::addPendingPeer (this=0x556f3e1f0fe0, node_id=...) at /opt/taraxa/src/network/taraxa_capability.cpp:90
#10 0x00007fd653465408 in taraxa::TaraxaCapability::onConnect (this=0x556f3e1f0fe0, session=...) at /opt/taraxa/src/network/taraxa_capability.cpp:230
```

some details
```
p peers_mutex_
$2 = {state = {shared_count = 1, exclusive = false, upgrade = false, exclusive_waiting_blocked = true}
```

**Comment by MatusKysel** [comment]
fixed by https://github.com/Taraxa-project/taraxa-node/pull/1032
