### ISSUE TITLE
Crash on selectPeers

### ISSUE THREAD

**Issue by MatusKysel** [Taraxa-project/taraxa-node#1138]
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f41935fb859 in __GI_abort () at abort.c:79
#2  0x00007f41936663ee in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f4193790285 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007f419366e47c in malloc_printerr (str=str@entry=0x7f4193792278 "malloc_consolidate(): invalid chunk size") at malloc.c:5347
#4  0x00007f419366ec58 in malloc_consolidate (av=av@entry=0x7f40b0000020) at malloc.c:4477
#5  0x00007f4193670e03 in _int_malloc (av=av@entry=0x7f40b0000020, bytes=bytes@entry=2048) at malloc.c:3699
#6  0x00007f4193673419 in __GI___libc_malloc (bytes=2048) at malloc.c:3066
#7  0x00007f419388db39 in operator new(unsigned long) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007f419473a936 in __gnu_cxx::new_allocator<dev::FixedHash<64u> >::allocate (this=0x7f40d6ffbf88, __n=32) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/ext/new_allocator.h:114
#9  std::allocator_traits<std::allocator<dev::FixedHash<64u> > >::allocate (__a=..., __n=32) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/alloc_traits.h:444
#10 std::_Vector_base<dev::FixedHash<64u>, std::allocator<dev::FixedHash<64u> > >::_M_allocate (this=0x7f40d6ffbf88, __n=32) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_vector.h:343
#11 std::vector<dev::FixedHash<64u>, std::allocator<dev::FixedHash<64u> > >::_M_realloc_insert<dev::FixedHash<64u> const&> (this=this@entry=0x7f40d6ffbf88, __position=
    {m_data = {_M_elems = "\233\203\037\244\003\200\000\240\361\000\000\000\000\000\000\000@\326\351\232?\177\000\000@\353c\332?\177\000\000\003*$\rt.$VDT\314\333\343\340$8\304\315\003\325\001Rh\270|\370z\240<\353\317\334"}}, __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/vector.tcc:440
#12 0x00007f4194738abf in std::vector<dev::FixedHash<64u>, std::allocator<dev::FixedHash<64u> > >::push_back (this=0x7f40d6ffbf88, __x=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_vector.h:1195
#13 taraxa::PeersState::selectPeers(std::function<bool (taraxa::TaraxaPeer const&)> const&) const (this=0x44e9800, _predicate=...) at /opt/taraxa/src/network/peers_state.cpp:64
#14 0x00007f419476207f in taraxa::TaraxaCapability::onNewBlockVerified (this=0x44e9400, block=..., proposed=<optimized out>) at /opt/taraxa/src/network/taraxa_capability.cpp:1086
#15 0x00007f4194730f59 in taraxa::Network::onNewBlockVerified(std::shared_ptr<taraxa::DagBlock> const&, bool)::$_1::operator()() const (this=0x7f40a0002af0) at /opt/taraxa/src/network/network.cpp:120
#16 std::_Function_handler<void (), taraxa::Network::onNewBlockVerified(std::shared_ptr<taraxa::DagBlock> const&, bool)::$_1>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:300
#17 0x00007f41947c566f in std::function<void (boost::system::error_code const&)>::operator()(boost::system::error_code const&) const (this=0x7f40d6ffc4e8, __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:688
#18 taraxa::util::ThreadPool::post(unsigned long, std::function<void (boost::system::error_code const&)>)::$_0::operator()() const (this=0x7f40d6ffc4e0) at /opt/taraxa/src/util/thread_pool.cpp:43
#19 boost::asio::asio_handler_invoke<taraxa::util::ThreadPool::post(unsigned long, std::function<void (boost::system::error_code const&)>)::$_0>(taraxa::util::ThreadPool::post(unsigned long, std::function<void (boost::system::error_code const&)>)::$_0&, ...) (function=...)
    at /root/.conan/data/boost/1.76.0/_/_/package/aec654dca71e1c640e76bca71e6f3e6dc428efe5/include/boost/asio/handler_invoke_hook.hpp:88
#20 boost_asio_handler_invoke_helpers::invoke<taraxa::util::ThreadPool::post(unsigned long, std::function<void (boost::system::error_code const&)>)::$_0, taraxa::util::ThreadPool::post(unsigned long, std::function<void (boost::system::error_code const&)>)::$_0>(taraxa::util::ThreadPool::post(unsigned long, std::function<void (boost::system::error_code const&)>)::$_0&, taraxa::util::ThreadPool::post(unsigned long, std::function<void (boost::system::error_code const&)>)::$_0&) (function=..., context=...) at /root/.conan/data/boost/1.76.0/_/_/package/aec654dca71e1c640e76bca71e6f3e6dc428efe5/include/boost/asio/detail/handler_invoke_helpers.hpp:54
#21 boost::asio::detail::executor_op<taraxa::util::ThreadPool::post(unsigned long, std::function<void (boost::system::error_code const&)>)::$_0, std::allocator<void>, boost::asio::detail::scheduler_operation>::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) (owner=0x17f0e80, base=<optimized out>)
    at /root/.conan/data/boost/1.76.0/_/_/package/aec654dca71e1c640e76bca71e6f3e6dc428efe5/include/boost/asio/detail/executor_op.hpp:70
#22 0x00007f41946e5b9e in boost::asio::detail::scheduler_operation::complete (this=0x7f40a08dcd40, owner=0x17f0e80, ec=..., bytes_transferred=<optimized out>) at /root/.conan/data/boost/1.76.0/_/_/package/aec654dca71e1c640e76bca71e6f3e6dc428efe5/include/boost/asio/detail/scheduler_operation.hpp:40
#23 boost::asio::detail::scheduler::do_run_one (this=this@entry=0x17f0e80, lock=..., this_thread=..., ec=...) at /root/.conan/data/boost/1.76.0/_/_/package/aec654dca71e1c640e76bca71e6f3e6dc428efe5/include/boost/asio/detail/impl/scheduler.ipp:486
#24 0x00007f41946e5661 in boost::asio::detail::scheduler::run (this=0x17f0e80, ec=...) at /root/.conan/data/boost/1.76.0/_/_/package/aec654dca71e1c640e76bca71e6f3e6dc428efe5/include/boost/asio/detail/impl/scheduler.ipp:204
#25 0x00007f41947c6281 in boost::asio::io_context::run (this=0x10) at /root/.conan/data/boost/1.76.0/_/_/package/aec654dca71e1c640e76bca71e6f3e6dc428efe5/include/boost/asio/impl/io_context.ipp:63
#26 taraxa::util::ThreadPool::start()::$_3::operator()() const (this=<optimized out>) at /opt/taraxa/src/util/thread_pool.cpp:20
#27 std::__invoke_impl<void, taraxa::util::ThreadPool::start()::$_3>(std::__invoke_other, taraxa::util::ThreadPool::start()::$_3&&) (__f=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:60
#28 std::__invoke<taraxa::util::ThreadPool::start()::$_3>(taraxa::util::ThreadPool::start()::$_3&&) (__fn=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:95
#29 std::thread::_Invoker<std::tuple<taraxa::util::ThreadPool::start()::$_3> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread:244
#30 std::thread::_Invoker<std::tuple<taraxa::util::ThreadPool::start()::$_3> >::operator()() (this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread:251
#31 std::thread::_State_impl<std::thread::_Invoker<std::tuple<taraxa::util::ThreadPool::start()::$_3> > >::_M_run() (this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread:195
#32 0x00007f41938b9de4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#33 0x00007f4193b1d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#34 0x00007f41936f8293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by MatusKysel** [comment]
removed by https://github.com/Taraxa-project/taraxa-node/pull/1178/
