### ISSUE TITLE
Devnet crash

### ISSUE THREAD

**Issue by MatusKysel** [Taraxa-project/taraxa-node#1542]
## Task Description
crash on devnet

```
#0  taraxa::Vote::getHash (this=0x0) at /opt/taraxa/libraries/types/vote/include/vote/vote.hpp:20
#1  taraxa::network::tarcap::VotesSyncPacketHandler::process (this=<optimized out>, packet_data=..., peer=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<taraxa::network::tarcap::TaraxaPeer, std::allocator<taraxa::network::tarcap::TaraxaPeer>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<taraxa::network::tarcap::TaraxaPeer, std::allocator<taraxa::network::tarcap::TaraxaPeer>, (__gnu_cxx::_Lock_policy)2>'

std::shared_ptr<taraxa::network::tarcap::TaraxaPeer> (use count 3, weak count 0) = {...})
    at /opt/taraxa/libraries/core_libs/network/src/tarcap/packets_handlers/votes_sync_packet_handler.cpp:105
#2  0x00007f7cbc2583af in taraxa::network::tarcap::PacketHandler::processPacket (this=0xc3b750, packet_data=...)
    at /opt/taraxa/libraries/core_libs/network/src/tarcap/packets_handlers/common/packet_handler.cpp:28
#3  0x00007f7cbc297782 in taraxa::network::tarcap::TarcapThreadPool::processPacket (this=0xe20cf0, worker_id=1)
    at /opt/taraxa/libraries/core_libs/network/src/tarcap/threadpool/tarcap_thread_pool.cpp:115
#4  0x00007f7cbae44de4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f7cbb0aa609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f7cbac83293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by MatusKysel** [comment]
@JakubFornadel it looks like your change https://github.com/Taraxa-project/taraxa-node/commit/d77821af0aec0fec2c7ae905de86a42106f96d5e broke this
