### ISSUE TITLE
Crash in periodicSendTransactions

### ISSUE THREAD

**Issue by MatusKysel** [Taraxa-project/taraxa-node#1689]
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f522c7f8700 (LWP 93))]
warning: Missing auto-load script at offset 0 in section .debug_gdb_scripts
of file /usr/local/lib/libcore_libs.so.
Use `info auto-load python-scripts [REGEXP]' to list them.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f52a7df1859 in __GI_abort () at abort.c:79
#2  0x00007f52a807a911 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f52a808638c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f52a80863f7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f52a80866fd in __cxa_rethrow () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f52a953a9e2 in std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >::_M_realloc_insert<std::vector<unsigned char, std::allocator<unsigned char> > const&> (this=0x7f5268123c78, __position=__position@entry=non-dereferenceable iterator for std::vector, 
    __args=std::vector of length -3712382276912166789, capacity 2213103442297958146 = {...})
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/vector.tcc:493
#7  0x00007f52a9546af4 in std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >::push_back (this=0x7f5268123c78, 
    __x=std::vector of length -3712382276912166789, capacity 2213103442297958146 = {...})
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_vector.h:1195
#8  taraxa::network::tarcap::TransactionPacketHandler::periodicSendTransactions (this=0x3b2edc0, transactions=...)
    at /opt/taraxa/libraries/core_libs/network/src/tarcap/packets_handlers/transaction_packet_handler.cpp:106
#9  0x00007f52a955f471 in taraxa::network::tarcap::TaraxaCapability::initPeriodicEvents(taraxa::NetworkConfig const&, std::shared_ptr<taraxa::PbftManager> const&, std::shared_ptr<taraxa::TransactionManager>, std::shared_ptr<taraxa::network::tarcap::PacketsStats>)::$_1::operator()() const (this=<optimized out>)
    at /opt/taraxa/libraries/core_libs/network/src/tarcap/taraxa_capability.cpp:113
#10 std::_Function_handler<void (), taraxa::network::tarcap::TaraxaCapability::initPeriodicEvents(taraxa::NetworkConfig const&, std::shared_ptr<taraxa::PbftManager> const&, std::shared_ptr<taraxa::TransactionManager>, std::shared_ptr<taraxa::network::tarcap::PacketsStats>)::$_1>::_M_invoke(std::_Any_data const&) (__functor=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:300
#11 0x00007f52a88fb5e4 in std::function<void ()>::operator()() const (this=0x7f526924bb18)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:688
#12 taraxa::util::ThreadPool::post_loop(taraxa::util::ThreadPool::Periodicity const&, std::function<void ()>)::$_4::operator()()
    (this=0x7f526924bb00) at /opt/taraxa/libraries/common/src/thread_pool.cpp:65
#13 std::_Function_handler<void (), taraxa::util::ThreadPool::post_loop(taraxa::util::ThreadPool::Periodicity const&, std::functi--Type <RET> for more, q to quit, c to continue without paging--
on<void ()>)::$_4>::_M_invoke(std::_Any_data const&) (__functor=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:300
#14 0x00007f52a88faa55 in std::function<void (boost::system::error_code const&)>::operator()(boost::system::error_code const&) const (this=0x7f522c7f7050, __args=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:688
#15 taraxa::util::ThreadPool::post(unsigned long, std::function<void (boost::system::error_code const&)>)::$_1::operator()<boost::system::error_code>(boost::system::error_code const&) const (this=0x7f522c7f7048, err_code=...)
    at /opt/taraxa/libraries/common/src/thread_pool.cpp:48
#16 boost::asio::detail::binder1<taraxa::util::ThreadPool::post(unsigned long, std::function<void (boost::system::error_code const&)>)::$_1, boost::system::error_code>::operator()() (this=0x7f522c7f7048)
    at /root/.conan/data/boost/1.76.0/_/_/package/aec654dca71e1c640e76bca71e6f3e6dc428efe5/include/boost/asio/detail/bind_handler.hpp:65
#17 boost::asio::asio_handler_invoke<boost::asio::detail::binder1<taraxa::util::ThreadPool::post(unsigned long, std::function<void (boost::system::error_code const&)>)::$_1, boost::system::error_code> >(boost::asio::detail::binder1<taraxa::util::ThreadPool::post(unsigned long, std::function<void (boost::system::error_code const&)>)::$_1, boost::system::error_code>&, ...) (
    function=...)
    at /root/.conan/data/boost/1.76.0/_/_/package/aec654dca71e1c640e76bca71e6f3e6dc428efe5/include/boost/asio/handler_invoke_hook.hpp:88
#18 boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder1<taraxa::util::ThreadPool::post(unsigned long, std::function<void (boost::system::error_code const&)>)::$_1, boost::system::error_code>, taraxa::util::ThreadPool::post(unsigned long, std::function<void (boost::system::error_code const&)>)::$_1>(boost::asio::detail::binder1<taraxa::util::ThreadPool::post(unsigned long, std::function<void (boost::system::error_code const&)>)::$_1, boost::system::error_code>&, taraxa::util::ThreadPool::post(unsigned long, std::function<void (boost::system::error_code const&)>)::$_1&) (function=..., context=...)
    at /root/.conan/data/boost/1.76.0/_/_/package/aec654dca71e1c640e76bca71e6f3e6dc428efe5/include/boost/asio/detail/handler_invoke_helpers.hpp:54
#19 boost::asio::detail::handler_work<taraxa::util::ThreadPool::post(unsigned long, std::function<void (boost::system::error_code const&)>)::$_1, boost::asio::any_io_executor, void>::complete<boost::asio::detail::binder1<taraxa::util::ThreadPool::post(unsigned long, std::function<void (boost::system::error_code const&)>)::$_1, boost::system::error_code> >(boost::asio::detail::binder1<taraxa::util::ThreadPool::post(unsigned long, std::function<void (boost::system::error_code const&)>)::$_1, boost::system::error_code>&, taraxa::util::ThreadPool::post(unsigned long, std::function<void (boost::system::error_code const&)>)::$_1&) (
--Type <RET> for more, q to quit, c to continue without paging--  
    this=0x7f522c7f70a8, function=..., handler=...)
    at /root/.conan/data/boost/1.76.0/_/_/package/aec654dca71e1c640e76bca71e6f3e6dc428efe5/include/boost/asio/detail/handler_work.hpp:501
#20 boost::asio::detail::wait_handler<taraxa::util::ThreadPool::post(unsigned long, std::function<void (boost::system::error_code const&)>)::$_1, boost::asio::any_io_executor>::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) (owner=0x3a49f10, base=<optimized out>)
    at /root/.conan/data/boost/1.76.0/_/_/package/aec654dca71e1c640e76bca71e6f3e6dc428efe5/include/boost/asio/detail/wait_handler.hpp:76
#21 0x00007f52a9491a1e in boost::asio::detail::scheduler_operation::complete (this=0x225c5d0, owner=0x3a49f10, ec=..., 
    bytes_transferred=<optimized out>)
    at /root/.conan/data/boost/1.76.0/_/_/package/aec654dca71e1c640e76bca71e6f3e6dc428efe5/include/boost/asio/detail/scheduler_operation.hpp:40
#22 boost::asio::detail::scheduler::do_run_one (this=this@entry=0x3a49f10, lock=..., this_thread=..., ec=...)
    at /root/.conan/data/boost/1.76.0/_/_/package/aec654dca71e1c640e76bca71e6f3e6dc428efe5/include/boost/asio/detail/impl/scheduler.ipp:486
#23 0x00007f52a94914e1 in boost::asio::detail::scheduler::run (this=0x3a49f10, ec=...)
    at /root/.conan/data/boost/1.76.0/_/_/package/aec654dca71e1c640e76bca71e6f3e6dc428efe5/include/boost/asio/detail/impl/scheduler.ipp:204
#24 0x00007f52a88fb3d1 in boost::asio::io_context::run (this=0x10)
    at /root/.conan/data/boost/1.76.0/_/_/package/aec654dca71e1c640e76bca71e6f3e6dc428efe5/include/boost/asio/impl/io_context.ipp:63
#25 taraxa::util::ThreadPool::start()::$_3::operator()() const (this=<optimized out>)
    at /opt/taraxa/libraries/common/src/thread_pool.cpp:19
#26 std::__invoke_impl<void, taraxa::util::ThreadPool::start()::$_3>(std::__invoke_other, taraxa::util::ThreadPool::start()::$_3&&) (__f=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:60
#27 std::__invoke<taraxa::util::ThreadPool::start()::$_3>(taraxa::util::ThreadPool::start()::$_3&&) (__fn=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/invoke.h:95
#28 std::thread::_Invoker<std::tuple<taraxa::util::ThreadPool::start()::$_3> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (
    this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread:244
#29 std::thread::_Invoker<std::tuple<taraxa::util::ThreadPool::start()::$_3> >::operator()() (this=<optimized out>)
--Type <RET> for more, q to quit, c to continue without paging--
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread:251
#30 std::thread::_State_impl<std::thread::_Invoker<std::tuple<taraxa::util::ThreadPool::start()::$_3> > >::_M_run() (
    this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread:195
#31 0x00007f52a80b2de4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#32 0x00007f52a8317609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#33 0x00007f52a7eee163 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by MatusKysel** [comment]
Crash - devnet - CN5
