### ISSUE TITLE
Node crash with stack trace

### ISSUE THREAD

**Issue by justinsnapp** [Taraxa-project/taraxa-node#807]
### Description

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f136b491859 in __GI_abort () at abort.c:79
#2  0x00007f136b86e951 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f136b87a47c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f136b87a4e7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f136b87a799 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00005604781f750a in boost::throw_exception<dev::UndersizeRLP> (e=...) at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/throw_exception.hpp:63
#7  boost::exception_detail::throw_exception_<dev::UndersizeRLP> (x=..., current_function=current_function@entry=0x56047878b130 "dev::RLP::RLP(dev::bytesConstRef, dev::RLP::Strictness)", 
    file=file@entry=0x56047878b0b0 "/opt/taraxa/submodules/taraxa-aleth/libdevcore/RLP.cpp", line=line@entry=32)
    at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/throw_exception.hpp:87
#8  0x00005604781f491b in dev::RLP::RLP (this=<optimized out>, _d=..., _s=<optimized out>)
    at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/exception/info.hpp:267
#9  0x0000560478165e3a in dev::p2p::Session::checkPacket (_msg=...) at /opt/taraxa/submodules/taraxa-aleth/libdevcore/vector_ref.h:124
#10 0x000056047816b7cd in dev::p2p::Session::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)>::operator()(boost::system::error_code, std::size_t) const (
    __closure=0x7f12e27fb038, ec=..., length=<optimized out>) at /opt/taraxa/submodules/taraxa-aleth/libp2p/Session.cpp:306
#11 0x000056047816bbc9 in boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >::operator()(const boost::system::error_code &, std::size_t, int) (this=0x7f12e27fb010, ec=..., bytes_transferred=<optimized out>, start=<optimized out>)
    at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/system/error_code.hpp:655
#12 0x000056047816d6fc in boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int>::operator() (this=0x7f12e27fb010) at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/detail/bind_handler.hpp:162
#13 boost::asio::detail::executor_function<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int>, std::allocator<void> >::do_complete(boost::asio::detail::executor_function_base *, bool) (base=0x7f12ac0ffa80, call=<optimized out>)
    at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/detail/executor_function.hpp:91
#14 0x0000560478135423 in boost::asio::detail::executor_function_base::complete (this=<optimized out>)
    at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/detail/executor_function.hpp:32
#15 boost::asio::executor::function::operator() (this=0x7f12e27fb0a8) at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/impl/executor.hpp:69
#16 boost::asio::asio_handler_invoke<boost::asio::executor::function> (function=...)
    at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/handler_invoke_hook.hpp:69
#17 boost_asio_handler_invoke_helpers::invoke<boost::asio::executor::function, boost::asio::executor::function> (context=..., function=...)
    at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#18 boost::asio::detail::handler_work<boost::asio::executor::function, boost::asio::system_executor, boost::asio::system_executor>::complete<boost::asio::executor::function> (this=<synthetic pointer>, 
    handler=..., function=...) at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/detail/handler_work.hpp:100
#19 boost::asio::detail::completion_handler<boost::asio::executor::function>::do_complete (owner=0x56047ccd2b30, base=<optimized out>)
    at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/detail/completion_handler.hpp:70
#20 0x0000560478135690 in boost::asio::detail::strand_service::dispatch<boost::asio::executor::function> (this=0x56047ccd7b30, impl=@0x7f12a0106730: 0x7f12a0005b20, handler=...)
    at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/system/error_code.hpp:579
#21 0x00005604781357b7 in boost::asio::io_context::strand::dispatch<boost::asio::executor::function, std::allocator<void> > (f=..., a=..., this=0x7f12a0106728)
    at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/impl/executor.hpp:54
#22 boost::asio::executor::impl<boost::asio::io_context::strand, std::allocator<void> >::dispatch (this=this@entry=0x7f12a0106710, f=...)
    at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/impl/executor.hpp:184
#23 0x000056047816d295 in boost::asio::executor::dispatch<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int>, std::allocator<void> > (a=..., f=..., this=<synthetic pointer>)
    at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/detail/executor_function.hpp:61
#24 boost::asio::detail::io_object_executor<boost::asio::executor>::dispatch<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int>, std::allocator<void> > (a=..., f=..., this=<synthetic pointer>)
    at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/detail/io_object_executor.hpp:128
#25 boost::asio::detail::handler_work<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::asio::detail::io_object_executor<boost::asio::executor>, boost::asio::detail::io_object_executor<boost::asio::executor> >::complete<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int> > (handler=..., function=..., this=<synthetic pointer>)
/root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/detail/handler_work.hpp:72
#26 boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::asio::detail::io_object_executor<boost::asio::executor> >::do_complete(void *, boost::asio::detail::operation *, const boost::system::error_code &, std::size_t) (owner=<optimized out>, base=<optimized out>) at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/detail/reactive_socket_recv_op.hpp:123
#27 0x000056047812c39f in boost::asio::detail::scheduler_operation::complete (bytes_transferred=0, ec=..., owner=0x56047ccd2b30, this=<optimized out>) at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/detail/scheduler_operation.hpp:40
#28 boost::asio::detail::scheduler::do_poll_one (ec=..., this_thread=..., lock=..., this=0x56047ccd2b30) at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/detail/impl/scheduler.ipp:581
#29 boost::asio::detail::scheduler::poll (this=0x56047ccd2b30, ec=...) at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/detail/impl/scheduler.ipp:267
#30 0x000056047811cc3a in boost::asio::io_context::poll (this=0x56047ccce2d8) at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/impl/io_context.ipp:93
#31 dev::p2p::Host::do_work (this=0x56047ccce2b0) at /opt/taraxa/submodules/taraxa-aleth/libp2p/Host.cpp:146
#32 0x000056047774162f in taraxa::Network::<lambda()>::operator() (__closure=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:1020
#33 std::_Function_handler<void(), taraxa::Network::Network(const taraxa::NetworkConfig&, const std::filesystem::__cxx11::path&, const dev::KeyPair&, std::shared_ptr<taraxa::DbStorage>, std::shared_ptr<taraxa::PbftManager>, std::shared_ptr<taraxa::PbftChain>, std::shared_ptr<taraxa::VoteManager>, std::shared_ptr<taraxa::NextVotesForPreviousRound>, std::shared_ptr<taraxa::DagManager>, std::shared_ptr<taraxa::DagBlockManager>, std::shared_ptr<taraxa::TransactionManager>)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/9/bits/std_function.h:300
#34 0x000056047775f2f5 in std::function<void ()>::operator()() const (this=0x7f12a02fd1f0) at /usr/include/c++/9/bits/std_function.h:683
#35 taraxa::util::ThreadPool::<lambda()>::operator() (__closure=0x7f12a02fd1f0) at /opt/taraxa/src/util/thread_pool.cpp:68
#36 std::_Function_handler<void(), taraxa::util::ThreadPool::post_loop(const taraxa::util::ThreadPool::Periodicity&, std::function<void()>)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/9/bits/std_function.h:300
#37 0x000056047775f76a in std::function<void (boost::system::error_code const&)>::operator()(boost::system::error_code const&) const (__args#0=..., this=0x7f12e27fb518) at /usr/include/c++/9/bits/std_function.h:683
#38 taraxa::util::ThreadPool::<lambda(const auto:2&)>::operator()<boost::system::error_code> (err_code=..., __closure=0x7f12e27fb510) at /opt/taraxa/src/util/thread_pool.cpp:51
#39 boost::asio::detail::binder1<taraxa::util::ThreadPool::post(uint64_t, taraxa::util::ThreadPool::asio_callback)::<lambda(const auto:2&)>, boost::system::error_code>::operator() (this=0x7f12e27fb510) at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/detail/bind_handler.hpp:65
#40 boost::asio::asio_handler_invoke<boost::asio::detail::binder1<taraxa::util::ThreadPool::post(uint64_t, taraxa::util::ThreadPool::asio_callback)::<lambda(const auto:2&)>, boost::system::error_code> > (function=...) at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/handler_invoke_hook.hpp:69
#41 boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder1<taraxa::util::ThreadPool::post(uint64_t, taraxa::util::ThreadPool::asio_callback)::<lambda(const auto:2&)>, boost::system::error_code>, taraxa::util::ThreadPool::post(uint64_t, taraxa::util::ThreadPool::asio_callback)::<lambda(const auto:2&)> > (context=..., function=...) at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#42 boost::asio::detail::asio_handler_invoke<boost::asio::detail::binder1<taraxa::util::ThreadPool::post(uint64_t, taraxa::util::ThreadPool::asio_callback)::<lambda(const auto:2&)>, boost::system::error_code>, taraxa::util::ThreadPool::post(uint64_t, taraxa::util::ThreadPool::asio_callback)::<lambda(const auto:2&)>, boost::system::error_code> (this_handler=0x7f12e27fb510, function=...) at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/detail/bind_handler.hpp:106
#43 boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder1<taraxa::util::ThreadPool::post(uint64_t, taraxa::util::ThreadPool::asio_callback)::<lambda(const auto:2&)>, boost::system::error_code>, boost::asio::detail::binder1<taraxa::util::ThreadPool::post(uint64_t, taraxa::util::ThreadPool::asio_callback)::<lambda(const auto:2&)>, boost::system::error_code> > (context=..., function=...) at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#44 boost::asio::detail::io_object_executor<boost::asio::executor>::dispatch<boost::asio::detail::binder1<taraxa::util::ThreadPool::post(uint64_t, taraxa::util::ThreadPool::asio_callback)::<lambda(const auto:2&)>, boost::system::error_code>, std::allocator<void> > (a=..., f=..., this=<synthetic pointer>) at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/detail/io_object_executor.hpp:119
#45 boost::asio::detail::handler_work<taraxa::util::ThreadPool::post(uint64_t, taraxa::util::ThreadPool::asio_callback)::<lambda(const auto:2&)>, boost::asio::detail::io_object_executor<boost::asio::executor>, boost::asio::detail::io_object_executor<boost::asio::executor> >::complete<boost::asio::detail::binder1<taraxa::util::ThreadPool::post(uint64_t, taraxa::util::ThreadPool::asio_callback)::<lambda(const auto:2&)>, boost::system::error_code> > (handler=..., function=..., this=<synthetic pointer>) at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/detail/handler_work.hpp:72
#46 boost::asio::detail::wait_handler<taraxa::util::ThreadPool::post(uint64_t, taraxa::util::ThreadPool::asio_callback)::<lambda(const auto:2&)>, boost::asio::detail::io_object_executor<boost::asio::executor> >::do_complete(void *, boost::asio::detail::operation *, const boost::system::error_code &, std::size_t) (owner=0x56047ad79350, base=<optimized out>) at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/detail/wait_handler.hpp:73
#47 0x00005604775cd08d in boost::asio::detail::scheduler_operation::complete (bytes_transferred=<optimized out>, ec=..., owner=0x56047ad79350, this=<optimized out>) at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/detail/scheduler_operation.hpp:40
#48 boost::asio::detail::scheduler::do_run_one (ec=..., this_thread=..., lock=..., this=<optimized out>) at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/detail/impl/scheduler.ipp:447
#49 boost::asio::detail::scheduler::run (this=0x56047ad79350, ec=...) at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/detail/impl/scheduler.ipp:200
#50 0x000056047775e246 in boost::asio::io_context::run (this=<optimized out>) at /root/.conan/data/boost/1.71.0/_/_/package/713919c5dcae28d8b809f1460df68ed236264c47/include/boost/asio/impl/io_context.ipp:63
#51 taraxa::util::ThreadPool::<lambda()>::operator() (__closure=<optimized out>) at /opt/taraxa/src/util/thread_pool.cpp:20
#52 std::__invoke_impl<void, taraxa::util::ThreadPool::start()::<lambda()> > (__f=...) at /usr/include/c++/9/bits/invoke.h:60
#53 std::__invoke<taraxa::util::ThreadPool::start()::<lambda()> > (__fn=...) at /usr/include/c++/9/bits/invoke.h:95
#54 std::thread::_Invoker<std::tuple<taraxa::util::ThreadPool::start()::<lambda()> > >::_M_invoke<0> (this=<optimized out>) at /usr/include/c++/9/thread:244
#55 std::thread::_Invoker<std::tuple<taraxa::util::ThreadPool::start()::<lambda()> > >::operator() (this=<optimized out>) at /usr/include/c++/9/thread:251
#56 std::thread::_State_impl<std::thread::_Invoker<std::tuple<taraxa::util::ThreadPool::start()::<lambda()> > > >::_M_run(void) (this=<optimized out>) at /usr/include/c++/9/thread:195
#57 0x00007f136b8a6d84 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#58 0x00007f136b7b6609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#59 0x00007f136b58e293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

### Environment

Devnet, boot node 2

##### Node version

`taraxa-node:pr-792-build-3`

**Comment by MatusKysel** [comment]
I think this https://github.com/Taraxa-project/taraxa-aleth/pull/21 resolved it
